### ISSUE TITLE
关于 | rimwindy's blog

### ISSUE THREAD

**Issue by rimwindy** [rimwindy/rimwindy.github.io#2]
https://www.mashiro.vip/about/ 

 关于

**Comment by chanshiyucx** [comment]
主题好看~~~

**Comment by rimwindy** [comment]
> @chanshiyucx
> 主题好看~~~ 

谢谢，不过这个主题基本没有修改多少2333，之前一直喜欢捣鼓WordPress的各种主题，最近准备静下心来写点~干货~氵文章（然而并没有）
