### ISSUE TITLE
Docker安装MySQL手记 | rimwindy's blog

### ISSUE THREAD

**Issue by rimwindy** [rimwindy/rimwindy.github.io#8]
https://www.mashiro.vip/post/Docker-with-MySQL/ 

 Docker安装MySQL手记

**Comment by chanshiyucx** [comment]
Docker 在手，天下我有~ 

对于一个后端初学者，docker 真是好用~

**Comment by rimwindy** [comment]
> @chanshiyucx
> Docker 在手，天下我有~ 
> 
> 对于一个后端初学者，docker 真是好用~

好用是好用，但Hyper-V与模拟器还有虚拟机不能共存。。。为了纸片人老婆，最后还是乖乖装回了MySQL(╥_╥)
